### ISSUE TITLE
Remove "0x" from listing

### ISSUE THREAD

**Issue by niccokunzmann** [niccokunzmann/mundraub-android#105]
If a plant has a count of zero, the count is not important.
We can remove it when the plant type is displayed.

Here, you can check if it is zero: 
[PlantListActivity.java](https://github.com/niccokunzmann/mundraub-android/blob/a8d9a8054dd1a0ff84846b3fd663a0a01c2de3ca/app/src/main/java/eu/quelltext/mundraub/activities/PlantListActivity.java#L220)

**Comment by JakubPalsa** [comment]
Can I start working on this?

**Comment by niccokunzmann** [comment]
@JakubPalsa Yes, you can :)

**Comment by niccokunzmann** [comment]
Thanks @JakubPalsa for solving this issue. If you have any questions, feel free to ask.
