### ISSUE TITLE
Use Plants from na ovoce

### ISSUE THREAD

**Issue by niccokunzmann** [niccokunzmann/mundraub-android#109]
https://na-ovoce.cz/web/
https://na-ovoce.cz/api/v1/fruit/
https://github.com/jsmesami/naovoce/blob/master/API.apib

**Comment by jsmesami** [comment]
Hi Nicco, sure you can integrate our data. If you are going to only fetch our POIs, you use the v1 fruit endpoint now,  if you are planning to integrate more, please consider waiting for larger changes, namely the new GraphQL API I am preparing. It will be ready in a few months. The v1 API will then be deprecated, but will be still around for a few more years. Cheers!

**Comment by niccokunzmann** [comment]
Roadmap:

- [ ] map categories, maybe add new ones
- [ ] hide all non-mundraub categories from the listing
- [ ] download plants in offline mode
- [ ] use offline mode as default or find out how to query in bounding box
- [ ] add marker for unknown category
- [ ] add markers for all categories
- [ ] adapt the map API and use marker categories from the app
- [ ] offline database must use string categories and not int[ OR assign other values to the na ovoce categories than mundraub would use (i.e. 1000+) - bad idea, not clean]

Login:
- [ ] implement login
- [ ] add different Online States for plants depending on provider
- [ ] implement upload
- [ ] implement deletion
