### ISSUE TITLE
Unable to set a location

### ISSUE THREAD

**Issue by Maxtille** [niccokunzmann/mundraub-android#110]
I am not able to set manually a location with the map (seems not to load) and the gps button doesn't work either for me. But I'm able to visualize other plants on the map of the main screen. 

I'm in lollipop Android version, and my GPS antenna may be dysfunctionning that's why I was trying to use the map to set location.

**Comment by niccokunzmann** [comment]
Hi, thanks for reporting. Two things can help more to go on with this:
- A screen shot
- the debug log - which is given then the app has external file system permissions. The log should show errors and more information about the map.

> (seems not to load)
- Is there no  map terrain / are there no streets?

>  other plants on the map of the main screen
Is there anything else visible except the markers?

**Comment by Maxtille** [comment]
Hi,
I will try to have a log and a screen shot this weekend.
So when I was trying to add plants the map didn't load (no street, no view, no marker)
But when I just explore existing markers, everything goes fine. I was not in satelite mode so streets etc appeared as on a map, even if it's a little bit heavy for my phone (not so much powefull) it ended working fine for this part of the app whereas in the window for adding markers it was not the case.

**Comment by niccokunzmann** [comment]
@Maxtille I changed how the map gets the position in 00bf6b97126d82981a48d73623606752eb5e2794. Now, this is possible on my phone. This is why I close this issue. If you see this bug in version 1.119+, you can comment.
