### ISSUE TITLE
fr_FR language makes build fail

### ISSUE THREAD

**Issue by niccokunzmann** [niccokunzmann/mundraub-android#130]
currently, we can not view translations because the build fails.
https://travis-ci.org/niccokunzmann/mundraub-android/jobs/428918875#L1465
This is because we added the fr_FR language.

Solution: We can remove it from Transifex.

Related: #125

**Comment by niccokunzmann** [comment]
I removed the language. Waiting for the build.

**Comment by niccokunzmann** [comment]
https://github.com/niccokunzmann/mundraub-android/releases/tag/v1.80 working

**Comment by niccokunzmann** [comment]
> Hey sorry for delay

No problem! I can not expect anyone to work in the same velocity on this
as I do.

> Hey sorry for delay, maybe it's because i still have not reviewed the
translation.

From my view, Android does not understand the file name
values-*fr_FR*.xml format. Only values-*fr*.xml, values-*en*.xml, ...
are present and work.
I did not want to find a solution for the case where we have sub-languages.
Because for the languages currently present, in Europe, I think they
understand each other's dialect.
I guess for India and other regions, this will be different.
We can open an issue for sub-languages.
Maybe then, one only needs to translate to fr-FR what is different from fr.

> And maybe there's a problem with tags or something ?

Could you tell me more about what you see?

**Comment by niccokunzmann** [comment]
> not reviewed

I do not think so, it just uses unreviewed and reviewed translations
because the review process takes too much time for me and I trust that
people want to help.
If you like to document how to translate to share which tricks and
experience you gathered, you are welcome!

**Comment by Maxtille** [comment]
I don't see an obligation in distinguishing french speaking of France from french speaking of Belgium and Switzerland, so if it's possible you could try setting the file name of french package as values-*fr*.xml ?
I would like to help on coding and solving issues too but I don't have any experience either in java or Android... So maybe later :) 

And for the documentation that's a good idea, don't you think we could open a wiki that would explain different functionnalities of the app and how to contribute on several way (translation, testing, coding, etc) ? 

> Could you tell me more about what you see?

Euh I don't actualy see anything special, it was just a nooby suposition in answer to you saying impossible to build :)

>  Solution: We can remove it from Transifex.

Remove what ? the french translation ? I hope this is temporary :)
I saw you added something with microsoft translation, you think it's possible to work with transifex and microsoft on the same project ?

**Comment by niccokunzmann** [comment]
> so if it's possible you could try setting the file name of french package as values-fr.xml ?

Yes, it is possible. There is only this file: https://github.com/niccokunzmann/mundraub-android/tree/v1.85/app/src/main/res/values-fr

> And for the documentation that's a good idea, don't you think we could open a wiki that would explain different functionalities of the app and how to contribute on several way (translation, testing, coding, etc) ?
Sure, if you like to do it this way.

I use the files in the docs folders: https://github.com/niccokunzmann/mundraub-android/tree/master/docs
You can use the wiki if you look on this page, there is a link to the wiki or the docs folder.

> Remove what ? the french translation ? I hope this is temporary :)

I removed fr-FR but fr is still there. I checked that I do not delete translations with this action. Currently, you have translated all to fr.

**Comment by niccokunzmann** [comment]
> I don't see an obligation in distinguishing french speaking of France
from french speaking of Belgium and Switzerland

I do not see it, too. So, currently, we only have *fr* and that is fine.

> so if it's possible you could try setting the file name of french
package as values-/fr/.xml ?

This is how it is now :)

> Solution: We can remove it from Transifex.

I removed fr-FR so now, there is only fr.

> I saw you added something with microsoft translation, you think it's
possible to work with transifex and microsoft on the same project ?

I activated the microsoft translator. You can press the
file:///home/firefox/Downloads/Screen%20Shot%202018-09-17%20at%2016.16.00.pngfile:///home/firefox/Downloads/Screen%20Shot%202018-09-17%20at%2016.16.00.pnglightning
icon to get a machine translation.
