### ISSUE TITLE
Add Maximum markers to serve to Settings

### ISSUE THREAD

**Issue by niccokunzmann** [niccokunzmann/mundraub-android#139]
Currently, you can only see 100 markers at most if you are offline.
I would like to change this in the settings in the offline section.

Code: https://github.com/niccokunzmann/mundraub-android/blob/master/app/src/main/java/eu/quelltext/mundraub/map/PlantsCache.java#L38

**Comment by ptelepcak** [comment]
Hi, I would like to take this one.

**Comment by niccokunzmann** [comment]
@ptelepcak Hi, you are welcome to do so. If you have any questions, let me know.

**Comment by niccokunzmann** [comment]
https://github.com/niccokunzmann/mundraub-android/pull/224 solves this.
