### ISSUE TITLE
Create notification about download

### ISSUE THREAD

**Issue by niccokunzmann** [niccokunzmann/mundraub-android#147]
In the settings, there is a download bar. Please add this download bar to the notifications.
It displays the progress of downloading off-line markers.

- [x] create a download notification #223 
- [ ] add the code from #223 to the [Progress Update](https://github.com/niccokunzmann/mundraub-android/blob/b3c97c078d8eefdc34653f00eea5601520194473/app/src/main/java/eu/quelltext/mundraub/activities/SettingsActivity.java#L65)
- [ ] consider moving the progress update to an independent class
- [ ] use the actual progress object to display the progress

**Comment by Bartal007** [comment]
Hi can I take this?

**Comment by niccokunzmann** [comment]
@Bartal007 Yes, you can. I will not do it.

**Comment by niccokunzmann** [comment]
@Bartal007 Thanks for working on this! As you can see, point one is done and other people can resume work on this issue.
