### ISSUE TITLE
Cannot set GPS position with GPS button on map

### ISSUE THREAD

**Issue by niccokunzmann** [niccokunzmann/mundraub-android#150]
If I click the GPS button, the map does not move to the GPS position and it flashes all the time.
This happens although the GPS symbol is filled and a GPS position should be given.

**Comment by niccokunzmann** [comment]
Using the GPS button works on the tablet but not on my phone. My phone needs quite some time to get a GPS position. Needs to be tested if this is really an issue.

**Comment by Maxtille** [comment]
I got the same issue on my phone (x5004 MEDION) but I'm not sure my GPS is still working fine (google map etc being very slow and unstable)

**Comment by niccokunzmann** [comment]
Solution: In case the API does not work, we can make this button to a  link which is clicked with the URL app://gps. We can then create a JAVA solution which opens the map at the GPS location.
