### ISSUE TITLE
Add edit and delete button in plant details

### ISSUE THREAD

**Issue by niccokunzmann** [niccokunzmann/mundraub-android#167]
I would like to see a button to edit and to delete the plant below the description of the plant.
The delete button should ask if the plant should be deleted.

**Comment by miro1016** [comment]
Hi, @niccokunzmann ... can I try do this?

**Comment by niccokunzmann** [comment]
@miro1016 Yes :) And you can ask me any time you like. E.g. if you get stuck.

**Comment by niccokunzmann** [comment]
yes! Exactly!

**Comment by miro1016** [comment]
It should be done :)

I have created pull request. Hopefully, it´s right.
