### ISSUE TITLE
Check and delete ic_launcher_round.png

### ISSUE THREAD

**Issue by niccokunzmann** [niccokunzmann/mundraub-android#192]
According to [zularizal](https://github.com/niccokunzmann/mundraub-android/pull/190#issuecomment-428988460), the  `ic_launcher_round.png` file can be deleted.
Please check if this is so and if deleting it is ok since it is no use, delete the file. 

Related: #101

**Comment by Sparow199** [comment]
Hello, your application is targeting Android API 25 (7.1) which support rounded launcher rounded icons. i made a PR which replace default launcher rounded icons. 


I think that it's interesting to target Android API 26 or above  to unlock the ability of using Adaptive icons. 
![adaptative_icons](https://user-images.githubusercontent.com/22281426/46915219-d2a0a980-cfa8-11e8-8a7c-3e2a199d6c61.PNG)

**Comment by niccokunzmann** [comment]
@Sparow199 Thanks for targeting this issue. With this app, I would like to be compatible to Android API version 9 at least or less. This is why I took the compatibility to 25.
If you like, you can open an issue and discuss changing the API version.
This issue is closed by your PR and I like to keep discussions to the topic of the issue and in open issues to not confuse when to close them and be able to keep track of past progress.

**Comment by niccokunzmann** [comment]
This will be live in v1.144.
