### ISSUE TITLE
[CSS] Use app colors for the map controls

### ISSUE THREAD

**Issue by niccokunzmann** [niccokunzmann/mundraub-android#197]
On the map, the app uses blue colors for the controls.
Please use the colors of the icon: yellow.

Documentation: https://github.com/niccokunzmann/mundraub-android/blob/master/docs/style.md#readme
Files: https://github.com/niccokunzmann/mundraub-android/tree/master/app/src/main/assets/map

**Comment by robkoro** [comment]
hi Can i work on this issue?

**Comment by niccokunzmann** [comment]
@robkoro Sure you can :) Please create a pull request as soon as it fits. It does not need to be complete to share code.

**Comment by niccokunzmann** [comment]
Thanks @robkoro ! I think, this closes the issue.
