### ISSUE TITLE
[Android] Show the icon when the app loads

### ISSUE THREAD

**Issue by niccokunzmann** [niccokunzmann/mundraub-android#198]
On the first screen, show the rotating icon in the place of the progress bar.
The progress bar can be there any way, just smaller.

Folder for Logo: https://github.com/niccokunzmann/mundraub-android/tree/master/images/app/Logo%20and%20icons
Activity: https://github.com/niccokunzmann/mundraub-android/blob/master/app/src/main/java/eu/quelltext/mundraub/activities/StartupActivity.java

**Comment by scanyboss** [comment]
Hi, can I take it ?

**Comment by RiotPharaoh** [comment]
Hi, I'm interested about solving your problem.

**Comment by niccokunzmann** [comment]
@scanyboss @RiotPharaoh If you like, you can work on it. You can even collaborate: As soon as there is a change, one of you creates the pull request and the other one tests and reviews the change. There is even [a way how you can improve each others' code](https://github.com/fossasia/labyrinth/blob/master/tasks/cooperate-on-a-pull-request.md#labyrinth-cooperate-on-a-pull-request).

Also, you can start working on a `good first issue` right away after you commented and you do not need to wait if you do not like to. Your comment will help others to come back to you and coordinate.

If you have any questions or get stuck, please feel free to drop a comment! Thanks for taking your time to help me and others.

**Comment by Renefedorcak** [comment]
Hello @niccokunzmann can i work on this or is this done ?

**Comment by niccokunzmann** [comment]
Sure, you can work on this!

**Comment by Renefedorcak** [comment]
Thank you. @niccokunzmann  if i good understand the issue, you want one of icons from the folder, which will be rotating above the progress bar during the loading. I am just the beginner, so sorry for this question.

**Comment by niccokunzmann** [comment]
#221 is the pull request. I will check before I close this issue.
