### ISSUE TITLE
No map images

### ISSUE THREAD

**Issue by programmin1** [niccokunzmann/mundraub-android#199]
I just updated today and I see broken images on the map.

**Comment by niccokunzmann** [comment]
That might be... Do you have a position of a plant with a broken image?
This might be related: https://github.com/niccokunzmann/mundraub-android/issues/140
If you go to the settings, you can enable the categories of fruitmap. Then, you will see that markers are missing.

**Comment by JTBrinkmann** [comment]
Assuming I have the same issue as op / @programmin1, this is what it looks like for me
![screenshot of the issue](https://user-images.githubusercontent.com/1379744/46921993-b7628800-d002-11e8-9200-dfb3c80ffd26.png)

**Comment by niccokunzmann** [comment]
Thanks for sharing the screen shot. This is interesting. If you enable external storage, you can attach the app log to see if there are errors in the background.

Does this work on your phone? https://niccokunzmann.github.io/mundraub-android/app/src/main/assets/map/examples/fullScreen.html

**Comment by jtracey** [comment]
This seems to be the relevant line from logcat (there are many others that are similar):

`SelectOfflineMapPartsAc: WebView: file:///android_asset/map/examples/fullScreen.html?createBoxes=true&lon=6.968046426773072&mapnikUrl=http%3A%2F%2Flocalhost%3A39768%2Ftiles%2Fosm%2F%24%7Bz%7D%2F%24%7By%7D%2F%24%7Bx%7D&earthUrl=http%3A%2F%2Flocalhost%3A39768%2Ftiles%2FArcGIS%2F%24%7Bz%7D%2F%24%7By%7D%2F%24%7Bx%7D&boxes=%5B%5D&browserGPS=false&lat=50.82075362541587#lon=6.968046426773072&lat=50.82075362541587&zoom=16&mapnikUrl=http%3A%2F%2Flocalhost%3A39768%2Ftiles%2Fosm%2F%24%7Bz%7D%2F%24%7By%7D%2F%24%7Bx%7D&earthUrl=http%3A%2F%2Flocalhost%3A39768%2Ftiles%2FArcGIS%2F%24%7Bz%7D%2F%24%7By%7D%2F%24%7Bx%7D&browserGPS=false&createBoxes=true&boxes=%5B%5D at line 0: Redirect from 'http://localhost:39768/tiles/ArcGIS/16/21993/34036' to 'https://services.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/16/21993/34036/' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access.` 

This is version 1.143, from f-droid. The link you posted works fine in a browser.

**Comment by niccokunzmann** [comment]
> Redirect from 'http://localhost:39768/tiles/ArcGIS/16/21993/34036' to 'https://services.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/16/21993/34036/' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access. sounds very specific.

A note from me: I have old devices and test compatibility for these. I can not test that as both my devices work. 

Here is the code: https://github.com/niccokunzmann/mundraub-android/blob/master/app/src/main/java/eu/quelltext/mundraub/map/MundraubMapAPIForApp.java#L102
Algorithm:
1. test if the tile is cached
2. if it is cached, return it
3. if it is not cached, redirect to the original URL

in (2) and (3), my guess is that one needs to add a line to allow javascript to access the values.
I did this already: https://github.com/niccokunzmann/mundraub-android/blob/master/app/src/main/java/eu/quelltext/mundraub/map/MundraubMapAPI.java#L130

About the process: I can add this line, making this guess. In two days, you know if it works. If not, this is quite a debug time. If any of you like to test that out, I am here to give assistance.

How would you like to proceed?

**Comment by niccokunzmann** [comment]
I think, it is related in a way because it talks about the header. It does not address the problem from my view because it talks about the access control if there is authentication. When the website communicates with the app-internal server, there is no authentication.

**Comment by Flexmaen** [comment]
Can confirm this bug on my phone too. External storage enabled, Android 8.1.

**Comment by niccokunzmann** [comment]
Thanks for taking the time to report.

How would you like to proceed with the bug?

**Comment by niccokunzmann** [comment]
I met somebody with a later smart phone, Android 6.
If you still encounter this issue, please comment so we can re-open the issue.
The fix is deployed in version 1.155.
