### ISSUE TITLE
No privacy policy statement.

### ISSUE THREAD

**Issue by HarryHeights** [niccokunzmann/mundraub-android#201]
Hello, I'm Harry. I came across your project and I like the concept of what it does. I decided to check out the repository and found you had no privacy policy statement which I think would be really necessary considering its functionalities have a lot to do with data collection and user privacy. I'm not entirely sure about this though but if that's the case then a privacy policy statement would be cool to have so end users are made away of what information they part with when your software is utilized. I'm a content creator and I contribute to open source projects by creating documents like privacy policy, FAQs etc . If you desire to have a policy statement drafted out, I.could do that for you.

**Comment by niccokunzmann** [comment]
Hi @HarryHeights. Yes, that is missing. I wonder how to add it. The app works like this:

1. There are three plant sources: Mundraub.org, Fruitmap.org and Na-Ovoce.cz. From them, we only   download the plants.
2.  Mundraub.org is special as plants are retrieved from there in online mode in a certain area,  when the map opens.
3. openstreetmap and the satellite map are used automatically when the map opens. 
4. staticmap is used automatically when plants are created to download an image of the plant position as a preview.
5. There are two platforms for upload: Mundraub.org, Na-Ovoce.cz. When the user tells the app to upload/logs in/ registers, more data is uploaded to the platforms. The password is saved in the app.

(2, 3, 4) are used automatically and possibly reveal the user's position and certainly the IP.
(5) reveals text, position, images, email, user name, category, password. 

I would like to make this app a community app which allows many communities to add their platforms in the future.

If such a statement is of value to you, it is of value to me and other users of the app. I appreciate your contribution and raising this issue.
How do you think would you like to continue and how can I support you?

**Comment by HarryHeights** [comment]
Normally what I do is gather intel from the software or  the developer and then I use the information to draft out a policy statement. The information you've provided is more than sufficient enough. 
The next step is for me to put the pieces together in a document using markdown text styling then I create a pull request. Then you can add the document in the software.  So other users can read the policy from within the app.

**Comment by niccokunzmann** [comment]
This sound good. I would also add a dialog box on the first start to ask if one wants to open the page.

**Comment by HarryHeights** [comment]
Yes that's a good idea. So that new users and even existing users are fully aware of the presence of a policy statement. I'll get to work right away.

**Comment by niccokunzmann** [comment]
@HarryHeights 
Issues #204 and #205 are future work.
Do you think something needs to be done for this issue or should it be closed?

**Comment by HarryHeights** [comment]
I've commented on those issues respectively. By the way do you have a blog or a website where you post contents about your project?

**Comment by niccokunzmann** [comment]
@HarryHeights I am closing this issue as it seems completed from my view. If you think, something needs to be done, you can comment and we can open it  again.
