### ISSUE TITLE
Review Privacy Policy for translation

### ISSUE THREAD

**Issue by niccokunzmann** [niccokunzmann/mundraub-android#204]
Thanks to @HarryHeights we have a [privacy policy](https://github.com/niccokunzmann/mundraub-android/blob/master/Privacy.md).

In order to translate it, we should make it stable so translations are not discarded all the time.

Roadmap:
- resolve the issues pointed out in the first draft
  - [x] optional: https://github.com/niccokunzmann/mundraub-android/pull/202#discussion_r225047833
  - [x] make app permissions fat for a fast reading and skipping through the text https://github.com/niccokunzmann/mundraub-android/pull/202#discussion_r225048070
  - [x] b1565a0 the software functions with less permissions https://github.com/niccokunzmann/mundraub-android/pull/202#discussion_r225048251
  - [x] https://github.com/niccokunzmann/mundraub-android/pull/202#discussion_r225049399
  - [x] https://github.com/niccokunzmann/mundraub-android/pull/202#discussion_r225049618
  - [ ] https://github.com/niccokunzmann/mundraub-android/pull/202#discussion_r225052971
- [x] add the Privacy.md to Transifex https://github.com/niccokunzmann/mundraub-android/blob/master/docs/translations.md#transifex-configuration

**Comment by HarryHeights** [comment]
I have gone through all the issues to be resolved. I think I made corrections about the software permissions in the last commit to the policy document. You can check that out. Then for the 30 days waiting period statement I'll change that.

**Comment by niccokunzmann** [comment]
Since #211 embedded the privacy policy as HTML, the process is as follows:

- [ ] b1565a0 the software functions with less permissions https://github.com/niccokunzmann/mundraub-android/pull/202#discussion_r225048251
- [ ] add the HTML file to transifex
