### ISSUE TITLE
Improve writing in README.md

### ISSUE THREAD

**Issue by JellyRollJunior** [niccokunzmann/mundraub-android#225]
The file's sentence structure could be improved.

**Comment by niccokunzmann** [comment]
@JellyRollJunior Thanks for reporting. I know of no point in the future when I could close this with certainty. I assigned you to this issue, so you can solve it.

**Comment by JellyRollJunior** [comment]
@niccokunzmann by the way, thanks for the fast reply. :-)

**Comment by niccokunzmann** [comment]
@JellyRollJunior Thanks for solving it. Sometimes I happen to be online at the right moment :)
