### ISSUE TITLE
Tranlation to Brazilian Portuguese

### ISSUE THREAD

**Issue by danilo-jlle** [niccokunzmann/mundraub-android#321]
Please add Portuguese - BR language.
I'll help to translate it.
Thanks.

**Comment by niccokunzmann** [comment]
Hello, thanks! I added the language! https://www.transifex.com/mundraub-android/mundraub-android-app/languages/

**Comment by danilo-jlle** [comment]
Translation complete.

**Comment by niccokunzmann** [comment]
I added a commit and a build should be under way.
