### ISSUE TITLE
App crashes on start

### ISSUE THREAD

**Issue by niccokunzmann** [niccokunzmann/mundraub-android#65]
Platforms:
- oneplus 5t running android 8.1
- Fairphone 2, Android 6.0.1, Prozessor Qualcomm MSM8974PRO-AA.

I am not able to reproduce this behavior because I do not have such a device.
If you have such a device, feel free to help out by posting the debug log file.

**Comment by Wasnix** [comment]
App crashes  on start

Platform: Xiaomi Redmi 5+, Android 7.1.2, 

Source of error: 

> java.io.FileNotFoundException: /storage/emulated/0/eu.quelltext.mundraub.log.txt (Permission denied)

[logcat-extract.txt](https://github.com/niccokunzmann/mundraub-android/files/2320842/logcat-extract.txt)

**Comment by niccokunzmann** [comment]
@Wasnix Thanks for reporting that! In https://github.com/niccokunzmann/mundraub-android/commit/12dbb7cd29eb9932177fb8e3aee2f98349dad207#diff-4bf4d85fde9690cc6c7736b129a70c3aR53 this error should be resolved. We can wait for a later release and check if it works.
Sadly, my Android phones have version 2.3 and 4, so I can not check whether asking for permissions works. I did not know that installs in later Androids do not ask for permissions and apps should ask for them, when they are running.

**Comment by programmin1** [comment]
Can't open app on LG with Android 7.

**Comment by programmin1** [comment]
Thank you... While it does run now it shows a blank screen and hitting +, add unknown plant, and tapping it shows a map that seems to have an api error. Also how do I sign up on mundraub, it seems there is no English version of the site?

**Comment by niccokunzmann** [comment]
@programmin1 Would you like to ask these questions as new issues as this is about the cash?
Thanks for reporting that the app does not crash any more!

**Comment by Michele64** [comment]
doesn't crash anymore, but blank screen and no login

**Comment by tbdal** [comment]
Hi same here: app crashes at start. 
Tested versions: 1.13 & 1.8
Platform: Sony z5 sumire with lineageos 14.1

**Comment by niccokunzmann** [comment]
@Michele64 @tbdal Thanks for the report, could you open a new issue for the blank screen and show a screen shot?
If existent, you can report the log file for more information about the app's internal state.

I will close this issue now as you confirmed that it is not crashing any more.

**Comment by tbdal** [comment]
here you go: https://github.com/niccokunzmann/mundraub-android/issues/75
