### ISSUE TITLE
Screen shots are not shown on F-Droid

### ISSUE THREAD

**Issue by niccokunzmann** [niccokunzmann/mundraub-android#69]
We have the screen shots in this folder:
https://github.com/niccokunzmann/mundraub-android/tree/v1.13/fastlane/metadata/android/en/images/phoneScreenshots
But we do not see them on F-Droid (veriosn 1.13): 
https://f-droid.org/en/packages/eu.quelltext.mundraub/

Description: https://fdroid.gitlab.io/fdroid-website/docs/All_About_Descriptions_Graphics_and_Screenshots/#in-the-apps-source-repository

**Comment by niccokunzmann** [comment]
https://gitlab.com/fdroid/fdroiddata/merge_requests/3592#note_97124287

**Comment by niccokunzmann** [comment]
Waiting for F-Droid to build.

**Comment by niccokunzmann** [comment]
F-Droid built version 1.22 and no screen shots are seen. https://f-droid.org/en/packages/eu.quelltext.mundraub/ Maybe we should look at other repositories with screen shots and what they do.

**Comment by niccokunzmann** [comment]
Forum Entry: https://forum.f-droid.org/t/screen-shots-not-showing-up/3720

**Comment by niccokunzmann** [comment]
Now, I am clueless. If somebody like to help, it is appreciated.

**Comment by mueller-ma** [comment]
Your screenshots are inside "fastlane/metadata/android/en/phoneScreenshots/", but they must be in "fastlane/metadata/android/en/**_images_**/phoneScreenshots/".

**Comment by niccokunzmann** [comment]
@mueller-ma Thanks for spotting this. I will see once v1.16 is deployed.

**Comment by niccokunzmann** [comment]
Now, in release 1.33, the screen shots are not showing up. ([v1.133: fastlane/metadata/android/en/images/phoneScreenshots](https://github.com/niccokunzmann/mundraub-android/tree/v1.133/fastlane/metadata/android/en/images/phoneScreenshots))

However, there are other apps which have screen shots working. We can copy code from there. Example: https://f-droid.org/en/packages/com.gitlab.ardash.appleflinger.android/

**Comment by niccokunzmann** [comment]
v1.143 and above will bring clarity

**Comment by niccokunzmann** [comment]
There it is: https://f-droid.org/en/packages/eu.quelltext.mundraub/ The screen shots are showing up.
