### ISSUE TITLE
No way to create account in English?

### ISSUE THREAD

**Issue by programmin1** [niccokunzmann/mundraub-android#85]
It appears there is no create account page in English. There is no create account function in the app and the site itself is not detecting English browser setting, or doesn't have an English version??

**Comment by niccokunzmann** [comment]
I think, there is only a German version of the web page. I guess, you like to register.

There is this page: https://mundraub.org/user/register
The fields are
- E-Mail-Adresse - E-mail-address
- Benutzername - username
- Passwort - password
- Passwort bestätigen - confirm password
- Ich habe die Mundräuber-Regeln sowie die AGB & Datenschutzerklärung gelesen und stimme ihnen zu. - I have read the rules and agree to them  
  Rules in short version, badly transtlated:
  - Please make sure, before you add a plant, that no property rights conflict
  - Please be careful with the plants and animals which live there. Picking for yourself and your own needs it allowed. Picking much and selling it requires a permit.
  - share the fruits of your endeavor and give back
  - get active in gardening the trees
- Ich möchte den mundraub-Newsletter erhalten. Die Abmeldung ist jederzeit möglich.  - I would like to receive the newsletter (German most probably)

If you would like to see it localized, please write to info @ mundraub.org and tell them that. I would like to see the service open-source and will tell them about how to localize it using a community.

I guessed you like to register. I do not really know your intention for writing this. What would it be?
