### ISSUE TITLE
Take the plants offline

### ISSUE THREAD

**Issue by niccokunzmann** [niccokunzmann/mundraub-android#96]
Mundraub.org allows downloading all plants at once.
```
wget -O plants.json 'https://mundraub.org/cluster/plant?bbox=-180.0,-90.0,180.0,90&zoom=18&cat=4,5,6,7,8,9,10,11,12,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37'
echo "$((`cat plants.json | wc -c` - `cat plants.json | sed s/nid/ni/g | wc -c`)) plants"
```

This takes about 4mb.

We can download them all and display them offline.

Possible solutions:
- download all plants as JSON, ask the API about one big JSON file and do the work in JavaScript
- use the sqlite database to query which plants are closest - which could be fastest

**Comment by niccokunzmann** [comment]
Current state: Settings and API are implemented. The database usage and download need to be tested.

**Comment by niccokunzmann** [comment]
Progress of ef20e27 : the plants can be downloaded and are present in the database
TODO: Use them from the API

**Comment by niccokunzmann** [comment]
The plants can be viewed in offline mode and the database can be updated.

**Comment by niccokunzmann** [comment]
Hi Dennis,

yes, it is not obvious. The real reason was that:

Updating the db means first deleting all plants and then adding the new ones.
I had the deletion still in there, when I added new plants, so that all were downloaded but only hazels 164 hazels were present because all others were deleted when the hazels were added.

Code: https://github.com/niccokunzmann/mundraub-android/commit/719a7fe7cb0a199478e3e5f4e67d744e39beb084#diff-515b59059312130b2ee5607268ef2538L167

**Comment by DKlemann** [comment]
Tricky! :-)

**Comment by DKlemann** [comment]
By the way - here is the refactored code:
```
 if (minLon > maxLon) {
                Log.d("rare case", "minLon " + minLon + " > maxLon" + maxLon);
            }
            if (minLat < maxLat) {
                Log.d("rare case", "minLat " + minLat + " > maxLat" + maxLat);
            }

            String selection =
                        Marker.COLUMN_LONGITUDE + " > ? and " +
                        Marker.COLUMN_LONGITUDE + " < ? and " +
                        Marker.COLUMN_LATITUDE + " > ? and " +
                        Marker.COLUMN_LATITUDE + " < ?";

            String[] selectionArgs = {
                    Double.toString(Math.min(minLon, maxLon)),
                    Double.toString(Math.max(minLon, maxLon)),
                    Double.toString(Math.min(minLat, maxLat)),
                    Double.toString(Math.max(minLat, maxLat)),
            };
```

**Comment by niccokunzmann** [comment]
Hi, thanks! The code makes it clear to understand.

I notice a mistake I made in the code.
I think, some testing can help to fix it.

The following idea:

Longitude goes from - 180 to +180.

If you have a window close to the earth and you look at +170 to -170, it
is a 20 degrees angle. +170 is minimum - which is a misleading term.
I think leftLon, rightLon, topLat and bottomLat would be much better and
clearer as they do not turn around given that north is at the top.
The test in the rare case should not be AND but should be OR.
I think, tests would clarify this. However, I never wrote a test for
Android, so I will for this.

If you like, you can create a pull request with your code. It has the
same mistake in my view but I am willing to merge it it you think it
should go in.

I never wrote a test for Android. Do you have recommendations?

**Comment by DKlemann** [comment]
Hi Nicco,

kannst du mir kurz schreiben, wie ich den Pull Request durchführen kann?
In Android Studio bekomme ich ein HTTP/403 zurück.

Die Sache mit dem Sichtfenster bei 180° östlicher bzw. westlicher Länge
ist in der Tat knifflig. Mir fällt spontan auch kein besserer Weg ein
als dann die Longitudes für die Abfrage in 2 Bereiche aufzuteilen, die
OR-verknüpft sind.
Latitude bleibt immerhin einheitlich, muss also nicht doppelt abgefragt
werden.
Im Prinzip sind dann noch Nord- und Südpol nicht abgedeckt - hier
erwarte ich aber wenig Abfragen und auch sowieso keine Ergebnisse.;-)

Bzgl. der (Unit-)Test bietet sich anscheinend JUnit an, wofür bereits
ein Plugin im Android Studio mit dabei ist.

Viele Grüße,
Dennis

Am 10.09.2018 um 21:29 schrieb Nicco Kunzmann:
